### ISSUE TITLE
/api/records/record_documents/ --- Apache/mod_wsgi request data read error: The timeout specified has expired.

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend#72]
Traceback (most recent call last):
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/http/request.py", line 391, in read
    return self._stream.read(*args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 40, in read
    result = self.buffer + self._read_limited(size - len(self.buffer))
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)

The above exception (Apache/mod_wsgi request data read error: The timeout specified has expired.) was the direct cause of the following exception:
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/law-orga-backend/apps/recordmanagement/views/encrypted_record_document.py", line 46, in create
    response = super().create(request, *args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 17, in create
    serializer = self.get_serializer(data=request.data)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/request.py", line 216, in data
    self._load_data_and_files()
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/request.py", line 279, in _load_data_and_files
    self._data, self._files = self._parse()
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/request.py", line 354, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/parsers.py", line 109, in parse
    data, files = parser.parse()
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/http/multipartparser.py", line 240, in parse
    for chunk in field_stream:
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/http/multipartparser.py", line 404, in __next__
    output = next(self._producer)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/http/multipartparser.py", line 536, in __next__
    for bytes in stream:
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/http/multipartparser.py", line 404, in __next__
    output = next(self._producer)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/http/multipartparser.py", line 467, in __next__
    data = self.flo.read(self.chunk_size)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/http/request.py", line 393, in read
    raise UnreadablePostError(*e.args) from e

Exception Type: UnreadablePostError at /api/records/record_documents/
Exception Value: Apache/mod_wsgi request data read error: The timeout specified has expired.

**Comment by danielmoessner** [comment]
This might help: [https://stackoverflow.com/questions/3823280/ioerror-request-data-read-error](https://stackoverflow.com/questions/3823280/ioerror-request-data-read-error)

**Comment by danielmoessner** [comment]
unreadable post will be catched now
see commit: 805bc2b52e5a215343fc1a8fd17344ebd233e700
