### ISSUE TITLE
Internal Server Error: /api/records/records/0000/ (Encryption/decryption failed.)

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend#77]
Traceback (most recent call last):
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/home/law-orga-backend/apps/recordmanagement/serializers/record.py", line 493, in get_entries
    aes_key_record = self.instance.get_aes_key(user=self.user, private_key_user=self.private_key_user)
  File "/home/law-orga-backend/apps/recordmanagement/models/record.py", line 250, in get_aes_key
    encryption.decrypt(private_key_user)
  File "/home/law-orga-backend/apps/recordmanagement/models/record.py", line 541, in decrypt
    super().decrypt(key)
  File "/home/law-orga-backend/apps/static/encryption.py", line 226, in decrypt
    decrypted_field = self.encryption_class.decrypt(getattr(self, field), key)
  File "/home/law-orga-backend/apps/static/encryption.py", line 192, in decrypt
    plaintext = private_key.decrypt(
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 433, in decrypt
    return _enc_dec_rsa(self._backend, self, ciphertext, padding)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 87, in _enc_dec_rsa
    return _enc_dec_rsa_pkey_ctx(backend, key, data, padding_enum, padding)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 151, in _enc_dec_rsa_pkey_ctx
    raise ValueError("Encryption/decryption failed.")

Request Method: GET
Exception Type: ValueError at /api/records/records/0000/
Exception Value: Encryption/decryption failed.
Request information:
USER: user: 0000; email: ----;

**Comment by danielmoessner** [comment]
Should be handled automatically with the new keys regenerate system.
